name: CI

# Run this workflow every time a new commit pushed to your repository
on: 
  push:
    branches: [ master ]
    tags:
    - v*
jobs:
  build:
    name: Build with ant
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: get version
        run: |
          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          echo "::set-env name=VERSION_NAME::$VERSION"  
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          echo "::set-env name=TAG_NAME::$VERSION"  
      - name: Git tag
        run: git tag -f snapshot && git push --tags -f
      - name: test
        run: echo  ${{ env.VERSION_NAME }}  ${{ env.TAG_NAME }}
      - uses: meeDamian/github-release@2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.TAG_NAME }}
          name: latest-snapshot
          prerelease: true
          gzip: false
          allow_override: true
          files: test:test1
